apiVersion: v1
kind: Pod
metadata:
  name: psql-client
  namespace: ops
spec:
  serviceAccountName: ops-reader
  containers:
  - name: psql
    image: postgres:15-alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  restartPolicy: Always
