apiVersion: v1
kind: ServiceAccount
metadata:
  name: ops-reader
  namespace: ops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-db-reader
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ops-reader-binding
subjects:
- kind: ServiceAccount
  name: ops-reader
  namespace: ops
roleRef:
  kind: ClusterRole
  name: tenant-db-reader
  apiGroup: rbac.authorization.k8s.io
