apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: pg-{{TENANT_NAME}}-store
  namespace: {{TENANT_NAME}}
spec:
  configuration:
    destinationPath: "s3://{{DO_SPACES_BUCKET}}/backups/{{TENANT_NAME}}"
    endpointURL: "{{DO_SPACES_ENDPOINT}}"
    serverName: pg-{{TENANT_NAME}}
    s3Credentials:
      accessKeyId:
        name: spaces-credentials
        key: DO_SPACES_ACCESS_KEY
      secretAccessKey:
        name: spaces-credentials
        key: DO_SPACES_SECRET_KEY
  wal:
    retention: "7d"
  data:
    retention: "7d"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-{{TENANT_NAME}}
  namespace: {{TENANT_NAME}}
spec:
  instances: 1
  storage:
    size: 1Gi
    storageClass: do-block-storage
  bootstrap:
    initdb:
      database: app
      owner: postgres
      secret:
        name: pg-{{TENANT_NAME}}-credentials
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"
      effective_cache_size: "512MB"
  backup:
    retentionPolicy: "7d"
    method: plugin
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      objectStore: pg-{{TENANT_NAME}}-store
