apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{TENANT_NAME}}-default-deny"
  namespace: {{TENANT_NAME}}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{TENANT_NAME}}-allow-dns"
  namespace: {{TENANT_NAME}}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{TENANT_NAME}}-allow-intra-namespace"
  namespace: {{TENANT_NAME}}
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: pg-{{TENANT_NAME}}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: cnpg-system
  # Allow communication from application pods
  - from:
    - podSelector:
        matchLabels:
          app: "{{TENANT_NAME}}-app"
    ports:
    - protocol: TCP
      port: 5432
  # Allow PostgreSQL cluster internal communication
  - from:
    - podSelector:
        matchLabels:
          cnpg.io/cluster: pg-{{TENANT_NAME}}
  egress:
  # Allow PostgreSQL cluster internal communication
  - to:
    - podSelector:
        matchLabels:
          cnpg.io/cluster: pg-{{TENANT_NAME}}
  # Allow communication to Kubernetes API server (for operator)
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 6443
  # Allow communication to DO Spaces for backups
  - to: []
    ports:
    - protocol: TCP
      port: 443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{TENANT_NAME}}-allow-public-ingress"
  namespace: {{TENANT_NAME}}
spec:
  podSelector:
    matchLabels:
      app: "{{TENANT_NAME}}-app"
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow public access to application
  - ports:
    - protocol: TCP
      port: 8080
  # Allow internal access (from same namespace only)
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 9090
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow connection to PostgreSQL
  - to:
    - podSelector:
        matchLabels:
          cnpg.io/cluster: pg-{{TENANT_NAME}}
    ports:
    - protocol: TCP
      port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{TENANT_NAME}}-allow-spaces-egress"
  namespace: {{TENANT_NAME}}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  egress:
  # Allow all pods to communicate with the operator in cnpg-system namespace
  - to:
    - namespaceSelector:
        matchLabels:
          name: cnpg-system
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{TENANT_NAME}}-allow-spaces-backup"
  namespace: {{TENANT_NAME}}
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: pg-{{TENANT_NAME}}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{TENANT_NAME}}-allow-intra-app"
  namespace: {{TENANT_NAME}}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: "{{TENANT_NAME}}-app"
    ports:
    - protocol: TCP
      port: 9090
