apiVersion: v1
kind: Service
metadata:
  name: "{{TENANT_NAME}}-public"
  namespace: {{TENANT_NAME}}
spec:
  type: LoadBalancer
  ports:
  - name: public
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: "{{TENANT_NAME}}-app"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{TENANT_NAME}}-internal"
  namespace: {{TENANT_NAME}}
spec:
  type: ClusterIP
  ports:
  - name: internal
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: "{{TENANT_NAME}}-app"
