name: Install CloudNativePG Operator Clusterwide

on:
  workflow_dispatch:

jobs:
  install-operator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Get kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ vars.K8S_CLUSTER_NAME }}

      - name: Install Helmfile
        run: |
          wget https://github.com/helmfile/helmfile/releases/download/v0.162.0/helmfile_0.162.0_linux_amd64.tar.gz
          tar -zxvf helmfile_0.162.0_linux_amd64.tar.gz
          sudo mv helmfile /usr/local/bin/helmfile

      - name: Deploy CNPG Operator with Helmfile
        run: |
          helmfile -f charts/helmfile.yaml sync
