name: Provision DigitalOcean Kubernetes Cluster

on:
  workflow_dispatch:

jobs:
  create-doks-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Verify doctl authentication
        run: doctl account get

      - name: Create DOKS cluster
        id: create_cluster
        run: |
          doctl kubernetes cluster create alaris-takehome-doks \
            --region nyc1 \
            --count 1 \
            --size s-1vcpu-2gb \
            --wait

      - name: Save kubeconfig
        run: doctl kubernetes cluster kubeconfig save alaris-takehome-doks
